# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestE():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_e(self):
    self.driver.get("https://ielts.neea.edu.cn/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.ID, "btn_log_goto").click()
    self.driver.find_element(By.LINK_TEXT, "考位查询").click()
    self.driver.find_element(By.CSS_SELECTOR, "#months > .checkbox:nth-child(2)").click()
    self.driver.find_element(By.ID, "btnSearch").click()
    element = self.driver.find_element(By.ID, "btnSearch")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    self.driver.find_element(By.CSS_SELECTOR, "#rightRange > #dialog .btn").click()
  
